version: '2.1'

services:
  rdbms:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=openoni
      - MYSQL_USER=openoni
      - MYSQL_PASSWORD=openoni
    volumes:
      - ./conf/mysql/:/etc/mysql/conf.d:Z
      - data-mariadb:/var/lib/mysql
  solr:
    image: solr:8.3-slim
    volumes:
      - data-solr:/var/solr
    command:
      - solr-precreate
      - openoni
  rais:
    image: uolibraries/rais
    environment:
      - RAIS_IIIFURL=${ONI_BASE_URL:-http://localhost}/images/iiif
      - RAIS_TILECACHELEN=250
      - RAIS_TILEPATH=/opt/openoni/data/batches
    volumes:
      # RAIS has to be able to read the batch sources, which, for dev, are most
      # likely stored in the local app directory
      - ./:/opt/openoni:z
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/opt/openoni:z
    ports:
      - ${HTTPPORT:-80}:80
    depends_on:
      - rdbms
    links:
      - rdbms
      - solr
      - rais
    environment:
      - APACHE_LOG_LEVEL=${APACHE_LOG_LEVEL:-warn}
      - ONI_BASE_URL
      - ONI_DB_HOST
      - ONI_DB_PORT
      - ONI_DB_NAME
      - ONI_DB_USER
      - ONI_DB_PASSWORD
      - ONI_DEBUG
      - ONI_HSTS_SECONDS
      - ONI_LOG_SQL
      - ONI_LOG_TO_FILE
      - ONI_SECRET_KEY
      - ONI_SOLR_URL

volumes:
  data-mariadb: {}
  data-solr: {}
